# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestingFinalMainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1108, 841)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(920, 630, 161, 151))
        self.startButton.setCheckable(False)
        self.startButton.setChecked(False)
        self.startButton.setObjectName("startButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 1091, 613))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidgetLeft = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidgetLeft.setMinimumSize(QtCore.QSize(381, 611))
        self.tabWidgetLeft.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tabWidgetLeft.setObjectName("tabWidgetLeft")
        self.scanTab = QtWidgets.QWidget()
        self.scanTab.setObjectName("scanTab")
        self.scanWidget = StackedExample(self.scanTab)
        self.scanWidget.setGeometry(QtCore.QRect(0, 0, 491, 581))
        self.scanWidget.setObjectName("scanWidget")
        self.tabWidgetLeft.addTab(self.scanTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.settingsWidget = CustomParamTree(self.settingsTab)
        self.settingsWidget.setGeometry(QtCore.QRect(0, 0, 491, 581))
        self.settingsWidget.setObjectName("settingsWidget")
        self.tabWidgetLeft.addTab(self.settingsTab, "")
        self.manTab = QtWidgets.QWidget()
        self.manTab.setObjectName("manTab")
        self.widget = StackedExample2(self.manTab)
        self.widget.setGeometry(QtCore.QRect(0, 0, 491, 581))
        self.widget.setObjectName("widget")
        self.tabWidgetLeft.addTab(self.manTab, "")
        self.testTab = QtWidgets.QWidget()
        self.testTab.setObjectName("testTab")
        self.tabWidgetLeft.addTab(self.testTab, "")
        self.horizontalLayout_3.addWidget(self.tabWidgetLeft)
        self.tabWidgetRight = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidgetRight.setObjectName("tabWidgetRight")
        self.liveTab = QtWidgets.QWidget()
        self.liveTab.setObjectName("liveTab")
        self.tabWidgetRight.addTab(self.liveTab, "")
        self.multiPlot = QtWidgets.QWidget()
        self.multiPlot.setObjectName("multiPlot")
        self.tabWidgetRight.addTab(self.multiPlot, "")
        self.fftTab = QtWidgets.QWidget()
        self.fftTab.setObjectName("fftTab")
        self.tabWidgetRight.addTab(self.fftTab, "")
        self.horizontalLayout_3.addWidget(self.tabWidgetRight)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(400, 630, 511, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeLeftTextLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timeLeftTextLabel.setFont(font)
        self.timeLeftTextLabel.setTextFormat(QtCore.Qt.AutoText)
        self.timeLeftTextLabel.setScaledContents(False)
        self.timeLeftTextLabel.setWordWrap(False)
        self.timeLeftTextLabel.setObjectName("timeLeftTextLabel")
        self.horizontalLayout.addWidget(self.timeLeftTextLabel)
        self.timeLeftLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timeLeftLabel.setFont(font)
        self.timeLeftLabel.setObjectName("timeLeftLabel")
        self.horizontalLayout.addWidget(self.timeLeftLabel)
        self.timeLeftHoursLAbel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timeLeftHoursLAbel.setFont(font)
        self.timeLeftHoursLAbel.setObjectName("timeLeftHoursLAbel")
        self.horizontalLayout.addWidget(self.timeLeftHoursLAbel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.expectrdFinishTextLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.expectrdFinishTextLabel.setFont(font)
        self.expectrdFinishTextLabel.setObjectName("expectrdFinishTextLabel")
        self.horizontalLayout_2.addWidget(self.expectrdFinishTextLabel)
        self.expectedFinishLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.expectedFinishLabel.setFont(font)
        self.expectedFinishLabel.setObjectName("expectedFinishLabel")
        self.horizontalLayout_2.addWidget(self.expectedFinishLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1108, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionSave_2)
        self.menuHelp.addAction(self.actionEdit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetLeft.setCurrentIndex(2)
        self.tabWidgetRight.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "START"))
        self.tabWidgetLeft.setTabText(self.tabWidgetLeft.indexOf(self.scanTab), _translate("MainWindow", "Scan"))
        self.tabWidgetLeft.setTabText(self.tabWidgetLeft.indexOf(self.settingsTab), _translate("MainWindow", "Settings"))
        self.tabWidgetLeft.setTabText(self.tabWidgetLeft.indexOf(self.manTab), _translate("MainWindow", "Man"))
        self.tabWidgetLeft.setTabText(self.tabWidgetLeft.indexOf(self.testTab), _translate("MainWindow", "Test"))
        self.tabWidgetRight.setTabText(self.tabWidgetRight.indexOf(self.liveTab), _translate("MainWindow", "Live"))
        self.tabWidgetRight.setTabText(self.tabWidgetRight.indexOf(self.multiPlot), _translate("MainWindow", "Multiplot"))
        self.tabWidgetRight.setTabText(self.tabWidgetRight.indexOf(self.fftTab), _translate("MainWindow", "FFT"))
        self.timeLeftTextLabel.setText(_translate("MainWindow", "Time Left:"))
        self.timeLeftLabel.setText(_translate("MainWindow", "03.00"))
        self.timeLeftHoursLAbel.setText(_translate("MainWindow", "h"))
        self.expectrdFinishTextLabel.setText(_translate("MainWindow", "Expected finish:"))
        self.expectedFinishLabel.setText(_translate("MainWindow", "19.37"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As..."))
        self.actionSave_2.setText(_translate("MainWindow", "Save"))
        self.actionEdit.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

from gui.instrumentControlWidgets import StackedExample2
from gui.ParamTreeTests import CustomParamTree
from gui.ScanTabWidgetTests import StackedExample
